### ISSUE TITLE
Get rid of W1029 warning in Delphi compile mode

### ISSUE THREAD

**Issue by jpluimers** [VSoftTechnologies/Delphi-Mocks#106]
Currently the compilation results in a lot of [W1029](http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/devcommon/cm_duplicate_ctor_dtor_xml.html) warnings that are only relevant for C++ code; see the compiler output below.

This might be as simple as `{$WARN SYMBOL_DEPRECATED OFF}` before and `{$WARN SYMBOL_DEPRECATED ON}` after the code (I don't think Delphi has a `$IFWARN` construct like it has `$IFOPT` and I'm not sure how to set compiling in Delphi and C++ mode apart; the last might be moot if Delphi-Mocks cannot be used from C++).

For completeness some references:

- http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/devcommon/cm_duplicate_ctor_dtor_xml.html 
- http://docwiki.embarcadero.com/RADStudio/en/W1029_Duplicate_%25s_%27%25s%27_with_identical_parameters_will_be_inacessible_from_C%2B%2B_%28Delphi%29
- https://marc.durdin.net/2012/05/delphi-xe2s-hidden-hints-and-warnings-options/
- https://stackoverflow.com/questions/19890053/duplicate-constructor-warning-in-delphi-xe2
- https://parnassus.co/useful-reference-about-disabling-specific-compiler-warnings/

Compiler output:

```
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAfter' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAfterWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtLeastOnce' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtLeastOnceWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtMost' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtMostWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateExactly' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateExactlyWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateNever' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateNeverWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateOnce' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateOnceWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAfter' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAfterWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtLeastOnce' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtLeastOnceWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtMost' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateAtMostWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateExactly' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateExactlyWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateNever' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateNeverWhen' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateOnce' with identical parameters will be inacessible from C++
[dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateOnceWhen' with identical parameters will be inacessible from C++
```

**Comment by vincentparrett** [comment]
I did actually try to get rid of this error, see in the code

//disable warnings about c++ compatibility, since we don't intend to support it.
{$WARN DUPLICATE_CTOR_DTOR OFF}
//for some reason this doesn't work.. this should override the project settings.

Seems like the option is ineffective, I didn't chase it up though, might be using it wrong?

**Comment by jpluimers** [comment]
@vincentparrett Via one of the links I mentioned (https://parnassus.co/useful-reference-about-disabling-specific-compiler-warnings) I found out *why* setting it in the source file having those constructors won't work:

> For each warning code (eg W1029) there is a corresponding name you can use either on the command line or in a {$WARN} directive to enable or disable it, restore it to its default on/off state, or promote it to an error.  For example, using the name for W1029 gives:
> 
> {$WARN DUPLICATE_CTOR_DTOR OFF}

...
> Some side notes:
...
> - This specific warning, W1029, has to be turned off in the project file not in the unit that generates the warning (in fact, the warning doesn’t specific a file or line number.)

Which means the warning and how to resolve it need to become part of the README.

My proposal for the text in the README are below. If you think it's OK I'll put in a pull request.

> By default the compiler will emit warnings like these for projects when using either of the `Delphi.Mocks.Behavior` or `Delphi.Mocks.Expectation` directly or indirectly:
> 
> [dcc32 Warning] W1029 Duplicate constructor 'TExpectation.CreateOnceWhen' with identical parameters will be inacessible from C++
> 
> They're harmless as DUnitX doesn't support C++. [This particular warning type cannot be disabled on the unit or source line level](https://parnassus.co/useful-reference-about-disabling-specific-compiler-warnings/) which means you have to disable it on the project level by either:
> 
> 1. adding `{$WARN DUPLICATE_CTOR_DTOR OFF}` anywhere to your `.dpr` project file
> 2. modifying the the Project Options for your project  (easiest is in the `All configurations - All platforms` target):
>    1. follow the path `Delphi Compiler`, `Hints and Warnings` in the treeview on the left
>    2. expand the `Output warnings` node in the listview on the right
>    3. set `Duplicate constructor/destructor with identical parameters will be inacessible from C++` to `Error`
> 
> A screenshot of the second option is below.
> 
> Note that the spelling mistake in `Duplicate constructor/destructor with identical parameters will be inacessible from C++` is how it is in the IDE, but that [as Google search string](https://www.google.com/search?q=Duplicate+constructor%2Fdestructor+with+identical+parameters+will+be+inacessible+from+C%2B%2B) it will give limited results, so here are some back-ground references:
> - Delphi 2007: [Duplicate %s '%s' with identical parameters will be inacessible from C++ (W1029)](http://docs.embarcadero.com/products/rad_studio/radstudio2007/RS2007_helpupdates/HUpdate3/EN/html/devcommon/cm_duplicate_ctor_dtor_xml.html)
> - Delphi 2009: [W1029: Duplicate %s '%s' with identical parameters will be inacessible from C++ (Delphi)](http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/devcommon/cm_duplicate_ctor_dtor_xml.html)
> - Delphi 2010 and up: [W1029 Duplicate %s '%s' with identical parameters will be inacessible from C++ (Delphi)](http://docwiki.embarcadero.com/RADStudio/en/W1029_Duplicate_%25s_%27%25s%27_with_identical_parameters_will_be_inacessible_from_C%2B%2B_%28Delphi%29)
> - Explanation about W1029: [Useful reference about disabling specific compiler warnings](https://parnassus.co/useful-reference-about-disabling-specific-compiler-warnings/)
> - [Delphi XE2’s hidden hints and warnings options](https://marc.durdin.net/2012/05/delphi-xe2s-hidden-hints-and-warnings-options/)
> - On warning W1029: [Duplicate constructor warning in Delphi XE2](https://stackoverflow.com/questions/19890053/duplicate-constructor-warning-in-delphi-xe2)
>
> [![Screenshot of the Project Options](https://www.dropbox.com/s/72qkqwv4wra3gfk/Screenshot%202016-11-30%2012.02.14.png?raw=1)](https://www.dropbox.com/s/72qkqwv4wra3gfk/Screenshot%202016-11-30%2012.02.14.png?dl=0)

(the screenshot needs to go into the repository; right now it's on DropBox as https://www.dropbox.com/s/72qkqwv4wra3gfk/Screenshot%202016-11-30%2012.02.14.png?dl=0 and directly linked as https://www.dropbox.com/s/72qkqwv4wra3gfk/Screenshot%202016-11-30%2012.02.14.png?raw=1)

**Comment by vincentparrett** [comment]
Closing this, I added a small comment in the expectations file.

**Comment by bogdanpolak** [comment]
@vincentparrett This is quite old discussion, but issue is still active and `{$WARN DUPLICATE_CTOR_DTOR OFF}` is not supported on the unit level (have to place in project file.
I think that this is good point to create project package (DPK) and and this compiler option over there. Vincent what do you think about `DelphiMock_Dxxx.dpk`?

I agree with @jpluimers that this comment should be visible in README
