### ISSUE TITLE
Need research if IStubSetup<T> can benefit from an overloaded method function WillReturn<TReturn>(const value : TReturn) : IWhen<T>; overload;

### ISSUE THREAD

**Issue by jpluimers** [VSoftTechnologies/Delphi-Mocks#107]
Right now I've quite some places with code like this:

```
procedure TMyProxyTests.GetStatus;
var
  lSubject: IMyInterface;
  lStatus: TMyRecord;
  lStatusValue: TValue;
  lMock: TMock<IMyInterface>;
begin
  lMock := TMock<IMyInterface>.Create();
// already complex lStatus initialisation
  lStatusValue := TValue.From(lStatus);
  lMock.Setup.WillReturn(lStatusValue).When.GetStatus();
  lMock.Setup.Expect.Once.When.GetStatus();
  lSubject := TMyProxy.Create(lMock);
  lSubject.GetStatus();
  lMock.Verify();
  Assert.Pass();
end;
```

It might be that if `IStubSetup<T>` has an overloaded method `function WillReturn<TReturn>(const value : TReturn) : IWhen<T>; overload;` that this code becomes more readable.

Need to try this out and see if there are no drawbacks (like the compiler choosing the wrong overload)

**Comment by sglienke** [comment]
Interfaces cannot have parameterized (i.e. generic) methods :(

**Comment by vincentparrett** [comment]
Closing due to language/compiler limitation.
