### ISSUE TITLE
Status of Delphi XE support

### ISSUE THREAD

**Issue by rmcginty** [VSoftTechnologies/Delphi-Mocks#113]
I looked at this awhile ago and saw the reasons why XE wasn't supported.  The comments alluded to a workaround for the (if I remember correctly) TVirtualMethodInterceptor, but when I got into trying to make it work, I quickly saw why it was likely not in place.  I know XE support is not on any priority list, but if there HAS been any progress, or if someone can point me in the right place on how to fix the primary issue, it might be something I can handle and test out.  Mocking manually (especially knowing there is a better way) is definitely no fun, but I can't move off of XE at this point for the main application I develop.

**Comment by vincentparrett** [comment]
I had intended to implement TVirtualInterface for XE, but it was difficult to do with really just copying what embarcadero had done. I do remember discussing this with Stephan (spring4d maintainer) as he had done just that, and it looked pretty much like embarcadero's code. I can talk to him about borrowing his code.

**Comment by vincentparrett** [comment]
Not going to put any effort into XE support now, closing this case. If you want to do it and submit a PR I'd be happy to take a look, provided it's not a direct copy of embarcadero's XE2 code.
