### ISSUE TITLE
Mocking an empty interface

### ISSUE THREAD

**Issue by joaofrassetto** [VSoftTechnologies/Delphi-Mocks#114]
I'm mocking the interface `IPrincipalModelo` that inherites from `IModelo`. When the test is running in DUnit, the moment the mock is created, this error is raised "class EMockNoRTTIException with message 'IPrincipalModelo does not have RTTI, specify {$M+}".

>{$M+}
>IPrincipalModelo = interface(IModelo)
>
>end;
>{$M-}

>{$M+}
>IModelo = interface
>
>end;
>{$M-}

If a method is inserted in `IPrincipalModelo` the test works. I know that it's not good to have an empty interface, so, what's should I do?

**Comment by vincentparrett** [comment]
Unfortunately, this is a limitation of the delphi compiler, if an interface has no methods, it will not generate rtti, and without that it's not possible to mock it.

**Comment by joaofrassetto** [comment]
@vincentparrett, do you know any workaround? Something that look good to solve this problem?

I'm new to issues in github, so, sorry if I do something wrong. And thanks for the answer.
