### ISSUE TITLE
Some units have (apparently unnecessarily) Windows in the uses clause

### ISSUE THREAD

**Issue by DelphiWorlds** [VSoftTechnologies/Delphi-Mocks#118]
The following units have Windows in the implementation uses clause, apparently for no reason:

Delphi.Mocks.AutoMock
Delphi.Mocks.MethodData
Delphi.Mocks.Proxy
Delphi.Mocks.Proxy.TypeInfo
Delphi.Mocks.WeakReference

This prevents these units from being compiled for (for example) macOS

**Comment by vincentparrett** [comment]
Thanks, I'll try and sort this out next week, pretty sure it's not needed.

**Comment by rhatherall** [comment]
Pretty sure you resolved this in fe3d8ec212276df7a2663819ef0c3d87d856bd10

**Comment by vincentparrett** [comment]
@rhatherall Yes, forgot to close this after committing. Closing now!
