### ISSUE TITLE
WillReturn for public class property with private getter

### ISSUE THREAD

**Issue by anvar1024** [VSoftTechnologies/Delphi-Mocks#143]
Is it possible to mock a public class property that has a private getter?
Example of class:
```pascal  
  TSample = class
  private
    function GetValue: Integer; virtual;
  public
    property Value: Integer read GetValue;
  end; 
```

I need to do something like this:
```pascal  
Mock.Setup.WillReturn(1).When.Value;
```

But its result is an error 'Setup called on non-virtual method'.
Does the framework provide the ability to work with such properties?

**Comment by vincentparrett** [comment]
Yes this should work, please show your full code for where you create the mock.

**Comment by anvar1024** [comment]
Here is the full code:

```pascal
unit sample_test;

interface

uses
  DUnitX.TestFramework, System.Classes, System.Generics.Collections, Delphi.Mocks, System.Types,
  System.SysUtils, RTTI;

type
  TSample = class
  private
    function GetValue: Integer; virtual;
  public
    property Value: Integer read GetValue;
  end;

  [TestFixture('TSample')]
  TSampleTest = class(TObject)
  public
    [Test]
    procedure TestProperty;
  end;

implementation

{ TSampleTest }

procedure TSampleTest.TestProperty;
var
  SampleMock: TMock<TSample>;
  Value: Int64;
begin
  // arrange
  SampleMock := TMock<TSample>.Create;
  SampleMock.Setup.WillReturn( TValue.From(1) ).When.Value;

  // act
  Value := SampleMock.Instance.Value;

  // assert
  // ...
end;

{ TSample }

function TSample.GetValue: Integer;
begin
  Result := 1;
end;

initialization
  TDUnitX.RegisterTestFixture(TSampleTest);

end.
```

**Comment by vincentparrett** [comment]
I think I was wrong about this - you should be doing the setup on the method not the property. If you look at how mocking is implemented, it's using TVirtualMethodInterceptor - which allows intercepting virtual methods, not properties.

**Comment by anvar1024** [comment]
Understood. Thanks for your reply.

TVirtualMethodInterceptor uses TRttiType.GetMethods which does not return private methods by default. Interestingly, a private method can still be obtained by its name: TRttiType.GetMethod(Name). It doesn't clear yet whether it can be used somehow.

Solved the problem by including private methods to RTTI:
{$RTTI EXPLICIT METHODS([vcPublic, vcProtected, vcPrivate])}
