### ISSUE TITLE
Mock does not behave correct

### ISSUE THREAD

**Issue by sglienke** [VSoftTechnologies/Delphi-Mocks#22]
A mock that does not have any expectations defined for a method behaves like a stub and does not report this method in Verify.

See the Sample1Main.Test.
I would expect the mock to complain directly or at least when calling Verify
about unexpected calls to SetMyProp and SetMyIndexedProp.

I also would expect that the call Bar(2) would be complained about because it has no expectation defined anywhere.

**Comment by staticcat** [comment]
So to get this definition clear, stubs are TMocks with no expectations assigned to them. If functions, properties, or procedures are accessed on the TMock while acting as a Stub, verify all should raise an exception. Is that correct?

If that is the case I suggest adding an option for "non-strict" stubs. This will allow you have a stub that you don't have to setup and simply returns default values for functions and properties. It also does not care what is called on it. In some tests, a passed Mock does not affect what is being tested.

**Comment by sglienke** [comment]
Since Delphi Mocks explicitly distinguishes mocks from stubs (you have explicit types for each) I would expect a mock without expectations to fail on any call attempt.

I however am using a different approach in the mocking libraries I work on (DSharp and Spring4D) to have only one type with 2 different behaviors one where any unspecified call raises an error and one where any unspecified call just goes through and returns the default value for the return type.

I would be fine with both but currently I consider the behavior as broken.

**Comment by staticcat** [comment]
Understand completely. I also think the behaviour in Delphi Mocks is not clear, and should be fixed. The only issue have have had in other libraries where the definition is as tight as you describe is in the following case:

I have an interface required by the class under test. The current test only calls into one function of the supplied interface to get a value. To do this I require a Mock of the supplied interface to set the returned value. The rub comes where this mock now fails at every other call that is not specifically setup. Say an Init method. 

In the test it is not important that the init method is called, or is not called. It is an implementation detail I shouldn't test as it will bind the test more tightly to the implementation. 

It is in this case that I suggest a "non-strict" mode for mocks. Where if anything is accessed off the mock that is not specifically setup, no error is raised. Also if a value is required then the default is returned just like a stub. 

Would the above be a suitable implementation?

**Comment by sglienke** [comment]
A stub does not prevent you from defining expectations, does it? So I use a stub plus defining the result value for that one method.

**Comment by vincentparrett** [comment]
I believe this is resolved with the .Setup.BehaviorMustBeDefined property. 
Closing, will reopen if that's not the case.
