### ISSUE TITLE
Problem with mock in Win64 mode.

### ISSUE THREAD

**Issue by ghost** [VSoftTechnologies/Delphi-Mocks#25]
Hello,

I have problem with using mocks in code compiled to Win64 platform. I wrote small example app which shows wrong values returned by mock:

  unit Unit1;

    interface

    uses
      Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
      Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.StdCtrls;

    type
      TForm1 = class(TForm)
        Button1: TButton;
        procedure Button1Click(Sender: TObject);
      private
        function TestDouble: Double;
        { Private declarations }
      public
        { Public declarations }
      end;

      ITest = interface(IInvokable)
        ['{DE3ACD58-A748-4528-A2A6-13C7A9247DB2}']
        function GetDate: TDateTime;
        property Date: TDateTime read GetDate;
      end;

    var
      Form1: TForm1;

    implementation

    uses
      Delphi.Mocks;

    {$R *.dfm}

    procedure TForm1.Button1Click(Sender: TObject);
    var
      mock: TMock<ITest>;
      test: ITest;
    begin
      mock := TMock<ITest>.Create;
      mock.Setup.WillReturn(Date).When.GetDate;
      Button1.Tag := Trunc(TestDouble);
      test := mock;
      Button1.Caption := DateToStr(test.GetDate);
    end;

    function TForm1.TestDouble: Double;
    begin
      Result := 123;
    end;

After execution of the  Button1Click procedure caption of the button is changed to wrong value (1900-05-02 value 123 in date format) when app is compiled for Win64 platform. When application is compiled for Win32 platform value is correct (current date). I think this is not Delphi Mocks related problem but TVirtualInterface related problem. Maybe it is corrected in newer version of Delphi. I'm using Delphi XE4 Pro.

**Comment by HoracioFilho** [comment]
@vincentparrett @asiwon Bugs related to TVirtualInterface and TVirtualMethodInterceptor were fixed in XE6 according http://qc.embarcadero.com/wc/qcmain.aspx?d=102627 and http://qc.embarcadero.com/wc/qcmain.aspx?d=99028 :D

**Comment by staticcat** [comment]
Closing as this appears to be fixed. Please re-submit if this is not the case.
