### ISSUE TITLE
Mocked Object - Allow calling base class functionality

### ISSUE THREAD

**Issue by staticcat** [VSoftTechnologies/Delphi-Mocks#36]
When mocking a class, an option should exists to call its base functionality. 

A simple example of this is as follows;

``` delphi
var
  deud : TMock<TStringList>;
begin
  deud := TMock<TStringList>.Create;
  deud.Instance.Add('2');
end;
```

In the above code the mock deud should allow the add. Currently the add is not defined so an exception is raised. If the option to call base functionality is specified, an exception should only be raised on attempting to create a class with abstract members which are then called.

**Comment by vincentparrett** [comment]
The issue here is that Add is a function, and has no default return value. Closing.
