### ISSUE TITLE
Add "function WillReturn<TReturn>(const AValue : TReturn) : IWhen<T>;" to TProxy<T>

### ISSUE THREAD

**Issue by staticcat** [VSoftTechnologies/Delphi-Mocks#37]
Currently in my mocking there is a great deal of writing the following;

``` Delphi
myMock.Setup.WillReturn(TValue.From<SomeType>(instanceOfType)).When.MyMethod;
```

This would be a little nicer to write as

``` Delphi
myMock.Setup.WillReturn<SomeType>(instanceOfType).When.MyMethod;
```

To do this TProxy<T> would require the following function to be added. 

``` Delphi
function WillReturn<TReturn>(const AValue : TReturn) : IWhen<T>;
```

Will look at adding this over the next day or so... unless someone else gets to it before me.

**Comment by sglienke** [comment]
I am pretty sure that is only possible with lambdas and generic helpers. Both which does not exist in Delphi. But that is how some frameworks do it in C#.

**Comment by vincentparrett** [comment]
Closing as not currently possible with delphi's implementation of generics on interfaces.
