### ISSUE TITLE
Add funcationality to call "EqualsTo"-Method of a record

### ISSUE THREAD

**Issue by jensweigele** [VSoftTechnologies/Delphi-Mocks#39]
Creating expectations of methods which takes a records as parameter is not really possible, because the TValueHelper (Delphi.Mocks.Helpers) just compares the pointers of the records (which are almost unequal when using them as method parameters).

I created an implementation which tries to call the "Equal"-Operator of a record (if it is defined). If it is not possible to call this (e.g. the record has no rtti-information or no equal operator is defined), the current behavior is used (compare pointers).

Should I create a pull request to submit this code?

**Comment by vincentparrett** [comment]
There is still no generic way to compare records in Delphi at this time (10.3) .. perhaps in the future we can check for an Equals operator but I have not found a way to do this with Rtti.
