### ISSUE TITLE
No way to capture all method calls when parameters are required.

### ISSUE THREAD

**Issue by staticcat** [VSoftTechnologies/Delphi-Mocks#42]
When there is a mock required for a class or interface and a setup is required on a particular method. If that method has parameters it becomes very hard to give the correct parameters to link the setup with. 

For example if we have the following interface and class to mock. 

```
type
  {$M+}
  IVisitor = interface;

  IElement = interface
    ['{A2F4744E-7ED3-4DE3-B1E4-5D6C256ACBF0}']
    procedure Accept(const AVisitor : IVisitor);
  end;

  IVisitor = interface
    ['{0D150F9C-909A-413E-B29E-4B869C6BC309}']
    procedure Visit(const AElement : IElement);
  end;

  TProjectSaveCheck = class(TInterfacedObject, IVisitor)
  public
    procedure Visit(const AElement : IElement);
  end;
  {$M-}
```

There is a problem trying to capture all calls to Visit, or even Accept. This means the following mock setup call needs to know the class or interface instance which is passed to the mock call. 

```
var 
    mockVisitor : TMock<IVisitor>;
    element : IElement;
begin
    mockVisitor.Setup.Expect.Once.When.Visit(????);

    element.Accept(mockVisitor);

    mockVisitor.Verify;
end;
```

The above case has been reduced for brevity sake, the constructor has been removed. Also the element might be the instance to pass in. But if element has more children, and we were to visit all of them this would then make this call fail. 

There needs to be away to specify conditions the parameters should meet for the expectation to be met, return result to be returned, etc. 

It would be nice to be able to write something along the lines of:

```
mockVisitor.Setup.Expect.Once.When.Visit(Is.Any<IVisitor>);
```

I don't believe this is possible at present however as there is no way to reverse where the value came from. Also there is no generic way to override methods to have funcs defined for all parameters.

**Comment by MartinSedgewick** [comment]
Could you not handle it slightly differently, like the following:

mockVisitor.Setup.Expect.Once.WhenAny.Visit

When I need to test a method is called, I write this as

mockVisitor.Setup.ExpectExactly( 'Visit', 1)

**Comment by vincentparrett** [comment]
Closing since we've not been able to implement this in any usable way.
