### ISSUE TITLE
Allow multiple return values to be specified for a method

### ISSUE THREAD

**Issue by natvincent** [VSoftTechnologies/Delphi-Mocks#56]
It would be really handy to be able to provide an array of TValues for the return values of a function so that on each call it will return the next value in the array.

This would remove the need to setup a will execute for the function and keep track of which call we are up to (which pollutes the code). 

For example:

```pascal
LListMock.Setup.WillReturnValues([-1, 2]).When.IndexOf(LItemMock);
```

**Comment by staticcat** [comment]
I believe this is now implemented by param matchers. Let me know if that is not the case. If we don't hear from anyone between now and the next review, we will assume this issue is done.

**Comment by staticcat** [comment]
Closing based on previous comment.
