### ISSUE TITLE
WillReturnDefault for stubs dont work anymore

### ISSUE THREAD

**Issue by gemeni2005** [VSoftTechnologies/Delphi-Mocks#74]
It seems that the Values for WillReturnDefault for stubs dont work anymore.
The function TMethodData.StubNoBehaviourRecordHit never returns the value of FReturnDefault.
In a previous version the TMethodData.RecordHit returns the FReturnDefault directly, when no BestVehaviour would be found.
For mocks it works.

**Comment by staticcat** [comment]
Thanks for reporting this. I will out what I occurring. If anyone else has a chance to write up some unit tests for this, or even a fix please submit it. My time is limited at present.

**Comment by vincentparrett** [comment]
Fixed, sorry it took so long!
