### ISSUE TITLE
Privileged instruction with methods which have a dynamic array as parameter

### ISSUE THREAD

**Issue by fabioxgn** [VSoftTechnologies/Delphi-Mocks#9]
DUnit unit test which reproduces the issue here: https://gist.github.com/fabioxgn/4965639

It will raise a privileged instruction in XE2 and a AV in XE3, it is raised in the Delphi.Mocks.Helpers SameValue method.

Looks like a Delphi bug to me, when I try to read the Left.Kind a get an "out of bounds" and a different number each time.

With a typed array the example works fine, as showed in the dunit test.

Another weird thing is that if the method only have the dynamic array as a parameter, it works. It just crashes when I add a second parameter to it.

**Comment by sglienke** [comment]
TRttiMethod.Invoke does not handle open arrays properly. The RTTI is there but it does not account that an open array are actually 2 parameters and passes it wrong.

**Comment by sglienke** [comment]
https://quality.embarcadero.com/browse/RSP-16317

**Comment by vincentparrett** [comment]
@sglienke Thanks for the reference.. love how they classified it as a new feature when it's clearly a bug, grrrrr.
