### ISSUE TITLE
Call to actual class method when mocking class with a non-virtual method

### ISSUE THREAD

**Issue by Rafnafnaf** [VSoftTechnologies/Delphi-Mocks#92]
Is this a desired behavior? It seems counterintuitive that the real method is called when trying to mock a class and calling a non-virtual method. Also, this prevents the mocking of non-owned classes as you cannot add virtual to the method if the class is not owned.

**Comment by vincentparrett** [comment]
Mocking of classes relies on TVirtualMethodInterceptor - which by it's very nature, only intercepts virtual methods, so this is just a limitation of how the mocking is implemented.
